artifact_dir : "artifact"

DataIngestionConfig :
  artifact_path : "artifact/data_ingestion"
  database_name : "MalwareModel"
  collection_name : "malwareData"

DataValidationConfig :
  artifact_path : "artifact/data_validation"
  data_path : "artifact/data_ingestion/ingested_data.csv"
  schema_path : "schema.yaml"

DataTransformationConfig :
  artifact_path : "artifact/data_transformation"
  data_path : "artifact/data_ingestion/ingested_data.csv"
  train_data_path : "artifact/data_transformation/train/"
  test_data_path : "artifact/data_transformation/test/"