artifact_dir : "artifact"

DataIngestionConfig :
  artifact_path : "artifact/data_ingestion"
  database_name : "MalwareModel"
  collection_name : "malwareData"

DataValidationConfig :
  artifact_path : "artifact/data_validation"
  data_path : "artifact/data_ingestion/ingested_data.csv"
  schema_path : "schema.yaml"
