ACCESS_ALL_DOWNLOADS: float64
ACCESS_CACHE_FILESYSTEM: float64
ACCESS_CHECKIN_PROPERTIES: float64
ACCESS_COARSE_LOCATION: float64
ACCESS_COARSE_UPDATES: float64
ACCESS_FINE_LOCATION: float64
ACCESS_LOCATION_EXTRA_COMMANDS: float64
ACCESS_MOCK_LOCATION: float64
ACCESS_MTK_MMHW: float64
ACCESS_NETWORK_STATE: float64
ACCESS_PROVIDER: float64
ACCESS_SERVICE: float64
ACCESS_SHARED_DATA: float64
ACCESS_SUPERUSER: float64
ACCESS_SURFACE_FLINGER: float64
ACCESS_WIFI_STATE: float64
ACCOUNT_MANAGER: float64
ACTIVITY_RECOGNITION: float64
ADD_VOICEMAIL: float64
ANT: float64
ANT_ADMIN: float64
AUTHENTICATE_ACCOUNTS: float64
AUTORUN_MANAGER_LICENSE_MANAGER: float64
AUTORUN_MANAGER_LICENSE_SERVICE(.autorun): float64
BATTERY_STATS: float64
BILLING: float64
BIND_ACCESSIBILITY_SERVICE: float64
BIND_APPWIDGET: float64
BIND_CARRIER_MESSAGING_SERVICE: float64
BIND_DEVICE_ADMIN: float64
BIND_DREAM_SERVICE: float64
BIND_GET_INSTALL_REFERRER_SERVICE: float64
BIND_INPUT_METHOD: float64
BIND_NFC_SERVICE: float64
BIND_PRINT_SERVICE: float64
BIND_REMOTEVIEWS: float64
BIND_TEXT_SERVICE: float64
BIND_TV_INPUT: float64
BIND_VOICE_INTERACTION: float64
BIND_VPN_SERVICE: float64
BIND_WALLPAPER: float64
BIND_goodwareTIFICATION_LISTENER_SERVICE: float64
BLUETOOTH: float64
BLUETOOTH_ADMIN: float64
BLUETOOTH_PRIVILEGED: float64
BODY_SENSORS: float64
BRICK: float64
BROADCAST_PACKAGE_REMOVED: float64
BROADCAST_SMS: float64
BROADCAST_STICKY: float64
BROADCAST_WAP_PUSH: float64
C2D_MESSAGE: float64
CALL_PHONE: float64
CALL_PRIVILEGED: float64
CAMERA: float64
CAPTURE_AUDIO_OUTPUT: float64
CAPTURE_SECURE_VIDEO_OUTPUT: float64
CAPTURE_VIDEO_OUTPUT: float64
CHANGE_COMPONENT_ENABLED_STATE: float64
CHANGE_CONFIGURATION: float64
CHANGE_DISPLAY_MODE: float64
CHANGE_NETWORK_STATE: float64
CHANGE_WIFI_MULTICAST_STATE: float64
CHANGE_WIFI_STATE: float64
CHECK_LICENSE: float64
CLEAR_APP_CACHE: float64
CLEAR_APP_USER_DATA: float64
CONTROL_LOCATION_UPDATES: float64
DATABASE_INTERFACE_SERVICE: float64
DELETE_CACHE_FILES: float64
DELETE_PACKAGES: float64
DEVICE_POWER: float64
DIAGgoodwareSTIC: float64
DISABLE_KEYGUARD: float64
DOWNLOAD_SERVICE: float64
DOWNLOAD_WITHOUT_goodwareTIFICATION: float64
DUMP: float64
EXPAND_STATUS_BAR: float64
EXTENSION_PERMISSION: float64
FACTORY_TEST: float64
FLASHLIGHT: float64
FORCE_BACK: float64
FULLSCREEN.FULL: float64
GET_ACCOUNTS: float64
GET_PACKAGE_SIZE: float64
GET_TASKS: float64
GET_TOP_ACTIVITY_INFO: float64
GLOBAL_SEARCH: float64
GOOGLE_AUTH: float64
GOOGLE_PHOTOS: float64
HARDWARE_TEST: float64
INJECT_EVENTS: float64
INSTALL_LOCATION_PROVIDER: float64
INSTALL_PACKAGES: float64
INSTALL_SHORTCUT: float64
INTERACT_ACROSS_USERS: float64
INTERNAL_SYSTEM_WINDOW: float64
INTERNET: float64
JPUSH_MESSAGE: float64
KILL_BACKGROUND_PROCESSES: float64
LOCATION_HARDWARE: float64
Label: object
Landroid/content/pm/PackageManager;->getInstalledApplications: float64
Landroid/content/pm/PackageManager;->getInstalledPackages: float64
Landroid/hardware/Camera;->open: float64
Landroid/hardware/Camera;->takePicture: float64
Landroid/location/LocationManager;->getLastKgoodwarewnLocation: float64
Landroid/media/AudioRecord;->startRecording: float64
Landroid/telephony/SmsManager;->sendMultipartTextMessage: float64
Landroid/telephony/SmsManager;->sendTextMessage: float64
Landroid/telephony/TelephonyManager;->getCellLocation: float64
Landroid/telephony/TelephonyManager;->getDeviceId: float64
Landroid/telephony/TelephonyManager;->getLine1Number: float64
Landroid/telephony/TelephonyManager;->getNetworkCountryIso: float64
Landroid/telephony/TelephonyManager;->getNetworkOperator: float64
Landroid/telephony/TelephonyManager;->getNetworkOperatorName: float64
Landroid/telephony/TelephonyManager;->getSimCountryIso: float64
Landroid/telephony/TelephonyManager;->getSimOperator: float64
Landroid/telephony/TelephonyManager;->getSimOperatorName: float64
Landroid/telephony/TelephonyManager;->getSimSerialNumber: float64
Lcom/google/android/gms/location/LocationClient;->getLastLocation: float64
Ldalvik/system/DexClassLoader;->loadClass: float64
Ljava/lang/Runtime;->exec: float64
Ljava/lang/System;->load: float64
Ljava/lang/System;->loadLibrary: float64
Ljava/lang/reflect/Method;->invoke: float64
Ljava/net/URL;->openConnection: float64
Ljavax/crypto/Cipher;->doFinal: float64
Lorg/apache/http/impl/client/DefaultHttpClient;->execute: float64
MANAGE_ACCOUNTS: float64
MANAGE_APP_TOKENS: float64
MANAGE_DOCUMENTS: float64
MAPS_RECEIVE: float64
MASTER_CLEAR: float64
MEDIA_BUTTON: float64
MEDIA_CONTENT_CONTROL: float64
MESSAGE: float64
MODIFY_AUDIO_SETTINGS: float64
MODIFY_PHONE_STATE: float64
MOUNT_FORMAT_FILESYSTEMS: float64
MOUNT_UNMOUNT_FILESYSTEMS: float64
NFC: float64
PERMISSION: float64
PERMISSION_RUN_TASKS: float64
PERSISTENT_ACTIVITY: float64
PLUGIN: float64
PROCESS_OUTGOING_CALLS: float64
READ: float64
READ_ATTACHMENT: float64
READ_AVESTTINGS: float64
READ_CALENDAR: float64
READ_CALL_LOG: float64
READ_CONTACTS: float64
READ_CONTENT_PROVIDER: float64
READ_DATA: float64
READ_DATABASES: float64
READ_EXTERNAL_STORAGE: float64
READ_FRAME_BUFFER: float64
READ_GMAIL: float64
READ_GSERVICES: float64
READ_HISTORY_BOOKMARKS: float64
READ_INPUT_STATE: float64
READ_LOGS: float64
READ_MESSAGES: float64
READ_OWNER_DATA: float64
READ_PHONE_STATE: float64
READ_PROFILE: float64
READ_SETTINGS: float64
READ_SMS: float64
READ_SOCIAL_STREAM: float64
READ_SYNC_SETTINGS: float64
READ_SYNC_STATS: float64
READ_USER_DICTIONARY: float64
READ_VOICEMAIL: float64
REBOOT: float64
RECEIVE: float64
RECEIVE_BOOT_COMPLETED: float64
RECEIVE_MMS: float64
RECEIVE_SIGNED_DATA_RESULT: float64
RECEIVE_SMS: float64
RECEIVE_USER_PRESENT: float64
RECEIVE_WAP_PUSH: float64
RECORD_AUDIO: float64
REORDER_TASKS: float64
REQUEST: float64
RESPOND: float64
RESTART_PACKAGES: float64
SDCARD_WRITE: float64
SEND: float64
SEND_RESPOND_VIA_MESSAGE: float64
SEND_SMS: float64
SET_ACTIVITY_WATCHER: float64
SET_ALARM: float64
SET_ALWAYS_FINISH: float64
SET_ANIMATION_SCALE: float64
SET_DEBUG_APP: float64
SET_ORIENTATION: float64
SET_POINTER_SPEED: float64
SET_PREFERRED_APPLICATIONS: float64
SET_PROCESS_LIMIT: float64
SET_TIME: float64
SET_TIME_ZONE: float64
SET_WALLPAPER: float64
SET_WALLPAPER_HINTS: float64
SIGNAL_PERSISTENT_PROCESSES: float64
STATUS_BAR: float64
STORAGE: float64
SUBSCRIBED_FEEDS_READ: float64
SUBSCRIBED_FEEDS_WRITE: float64
SYSTEM_ALERT_WINDOW: float64
TRANSMIT_IR: float64
UNINSTALL_SHORTCUT: float64
UPDATE_DEVICE_STATS: float64
USES_POLICY_FORCE_LOCK: float64
USE_CREDENTIALS: float64
USE_FINGERPRINT: float64
USE_SIP: float64
VIBRATE: float64
WAKE_LOCK: float64
WRITE: float64
WRITE_APN_SETTINGS: float64
WRITE_AVSETTING: float64
WRITE_CALENDAR: float64
WRITE_CALL_LOG: float64
WRITE_CONTACTS: float64
WRITE_DATA: float64
WRITE_DATABASES: float64
WRITE_EXTERNAL_STORAGE: float64
WRITE_GSERVICES: float64
WRITE_HISTORY_BOOKMARKS: float64
WRITE_INTERNAL_STORAGE: float64
WRITE_MEDIA_STORAGE: float64
WRITE_OWNER_DATA: float64
WRITE_PROFILE: float64
WRITE_SECURE_SETTINGS: float64
WRITE_SETTINGS: float64
WRITE_SMS: float64
WRITE_SOCIAL_STREAM: float64
WRITE_SYNC_SETTINGS: float64
WRITE_USER_DICTIONARY: float64
WRITE_VOICEMAIL: float64
_id: object
activityCalled: float64
